;; -*- mode: lisp; syntax: common-lisp; -*-

(in-package "COMMON-LISP-USER")

(defpackage "ETSY"
  (:documentation "A bridge from common lisp to API of etsy.com.")
  (:use "COMMON-LISP")
  (:export 
   ;; Globals
   "*API-KEY*"
   ;; Classes
   "USER"
   "SHOP"
   "SHOP-SECTION"
   "LISTING"
   "GIFT-GUIDE"
   "FEEDBACK"
   "API-METHOD"
   ;; API METHODS
   "GET-USER-DETAILS"
   "GET-FAVORERS-OF-SHOP"
   "GET-FAVORERS-OF-LISTING"
   "GET-USERS-BY-NAME"
   "GET-SHOP-DETAILS"
   "GET-FEATURED-SELLERS"
   "GET-SHOPS-BY-NAME"
   "GET-FAVORITE-SHOPS-OF-USER"
   "GET-LISTING-DETAILS"
   "GET-ALL-LISTINGS"
   "GET-SHOP-LISTINGS"
   "GET-FEATURED-DETAILS"
   "GET-FRONT-FEATURED-LISTINGS"
   "GET-FAVORITE-LISTINGS-OF-USER"
   "GET-GIFT-GUIDE-LISTINGS"
   "GET-LISTINGS-BY-KEYWORD"
   "GET-LISTINGS-BY-TAGS"
   "GET-LISTINGS-BY-MATERIALS"
   "GET-LISTINGS-BY-CATEGORY"
   "GET-LISTINGS-BY-COLOR"
   "GET-LISTINGS-BY-COLOR-AND-KEYWORDS"
   "GET-TOP-TAGS"
   "GET-CHILD-TAGS"
   "GET-TOP-CATEGORIES"
   "GET-CHILD-CATEGORIES"
   "GET-GIFT-GUIDES"
   "GET-FEEDBACK"
   "GET-FEEDBACK-FOR-USER"
   "GET-FEEDBACK-AS-BUYER"
   "GET-FEEDBACK-AS-SELLER"
   "GET-FEEDBACK-FOR-OTHERS"
   "GET-METHOD-TABLE"
   "GET-SERVER-EPOCH"
   "PING"))
